const MenuItems=[
    {
        title:'Home',
        url:'#',
        cName:'nav-links'
    },
    {
        title:'About',
        url:'#',
        cName:'nav-links'
    },
    {
        title:'Services',
        url:'#',
        cName:'nav-links'
    },
    {
        title:'Portfolio',
        url:'#',
        cName:'nav-links'
    },
    {
        title:'Testimonials',
        url:'#',
        cName:'nav-links'
    },
    {
        title:'Team',
        url:'#',
        cName:'nav-links'
    },
    {
        title:'News',
        url:'#',
        cName:'nav-links'
    },
    {
        title:'ontact-us',
        url:'#',
        cName:'nav-links'
    },

]